<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="ANSI">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Atividades 2º Semestre</title>
    <link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="./style.css">
    <link rel="shortcut icon" type="image/x-icon" href="./img/favicon.png">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.12/jquery.mask.min.js"></script>
</head>
<style>
  img[src="https://cdn.000webhost.com/000webhost/logo/footer-powered-by-000webhost-white2.png"]{
display:none!important;
}
</style>
<body onload="load()">
    <div id="preloader">
        <div class="inner">
          <div class="loadingio-spinner-spin-f5y98bevnpb"><div class="ldio-gvobqusg6p9">
          <div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div>
          </div></div>
          <style type="text/css">
          @keyframes ldio-gvobqusg6p9 {
            0% {
              opacity: 1;
              backface-visibility: hidden;
              transform: translateZ(0) scale(1.5,1.5);
            } 100% {
              opacity: 0;
              backface-visibility: hidden;
              transform: translateZ(0) scale(1,1);
            }
          }
          .ldio-gvobqusg6p9 div > div {
            position: absolute;
            width: 24px;
            height: 24px;
            border-radius: 50%;
            background: #f8f9fa;
            animation: ldio-gvobqusg6p9 1s linear infinite;
          }.ldio-gvobqusg6p9 div:nth-child(1) > div {
            left: 148px;
            top: 88px;
            animation-delay: -0.875s;
          }
          .ldio-gvobqusg6p9 > div:nth-child(1) {
            transform: rotate(0deg);
            transform-origin: 160px 100px;
          }.ldio-gvobqusg6p9 div:nth-child(2) > div {
            left: 130px;
            top: 130px;
            animation-delay: -0.75s;
          }
          .ldio-gvobqusg6p9 > div:nth-child(2) {
            transform: rotate(45deg);
            transform-origin: 142px 142px;
          }.ldio-gvobqusg6p9 div:nth-child(3) > div {
            left: 88px;
            top: 148px;
            animation-delay: -0.625s;
          }
          .ldio-gvobqusg6p9 > div:nth-child(3) {
            transform: rotate(90deg);
            transform-origin: 100px 160px;
          }.ldio-gvobqusg6p9 div:nth-child(4) > div {
            left: 46px;
            top: 130px;
            animation-delay: -0.5s;
          }
          .ldio-gvobqusg6p9 > div:nth-child(4) {
            transform: rotate(135deg);
            transform-origin: 58px 142px;
          }.ldio-gvobqusg6p9 div:nth-child(5) > div {
            left: 28px;
            top: 88px;
            animation-delay: -0.375s;
          }
          .ldio-gvobqusg6p9 > div:nth-child(5) {
            transform: rotate(180deg);
            transform-origin: 40px 100px;
          }.ldio-gvobqusg6p9 div:nth-child(6) > div {
            left: 46px;
            top: 46px;
            animation-delay: -0.25s;
          }
          .ldio-gvobqusg6p9 > div:nth-child(6) {
            transform: rotate(225deg);
            transform-origin: 58px 58px;
          }.ldio-gvobqusg6p9 div:nth-child(7) > div {
            left: 88px;
            top: 28px;
            animation-delay: -0.125s;
          }
          .ldio-gvobqusg6p9 > div:nth-child(7) {
            transform: rotate(270deg);
            transform-origin: 100px 40px;
          }.ldio-gvobqusg6p9 div:nth-child(8) > div {
            left: 130px;
            top: 46px;
            animation-delay: 0s;
          }
          .ldio-gvobqusg6p9 > div:nth-child(8) {
            transform: rotate(315deg);
            transform-origin: 142px 58px;
          }
          .loadingio-spinner-spin-f5y98bevnpb {
            width: 200px;
            height: 200px;
            display: inline-block;
            overflow: hidden;
            background: rgba(NaN, NaN, NaN, 0);
          }
          .ldio-gvobqusg6p9 {
            width: 100%;
            height: 100%;
            position: relative;
            transform: translateZ(0) scale(1);
            backface-visibility: hidden;
            transform-origin: 0 0; /* see note above */
          }
          .ldio-gvobqusg6p9 div { box-sizing: content-box; }
          /* generated by https://loading.io/ */
          </style>
        </div>
    </div>